### ISSUE TITLE
TZ: Rocket Leff causing GI to stay off

### ISSUE THREAD

**Issue by SonnyJim** [bcd/freewpc#10]
Randomly the Rocket leff causes the GI to stay off, hitting a feature that cycles the GI brings them on again

**Comment by bcd** [comment]
Is this still happening?  There was a commit on 7 Sep, id 616863530, which fixed a problem that sounds similar.  Do you have these changes in the code you are running?

**Comment by SonnyJim** [comment]
I've managed to get the latest code and the problem seems to have gone.

**Comment by bcd** [comment]
OK, that's good to know.
