### ISSUE TITLE
config.example needs updating

### ISSUE THREAD

**Issue by SonnyJim** [bcd/freewpc#12]
Very minor issue, the following line needs to be updated:
# Set to the version of gcc6809 installed.
# The 4.3.x releases are recommended, although 4.2.x releases
# should still work.
# GCC_VERSION := 3.4.6
# GCC_VERSION := 4.2.3
# GCC_VERSION := 4.3.1
# GCC_VERSION := 4.4.0

to:
# GCC_VERSION := 4.3.4

To be the same as current gcc6809 version.

**Comment by SonnyJim** [comment]
Closed

**Comment by bcd** [comment]
OK thanks.
