### ISSUE TITLE
flipper_override_pulse() and flippers no longer work in test

### ISSUE THREAD

**Issue by SonnyJim** [bcd/freewpc#16]
I should image it's something to do with drivers/duty2.ct?

**Comment by bcd** [comment]
No, that file isn't being used yet.  Not sure what the problem is.  I'll try to reproduce it.

**Comment by bcd** [comment]
I can see that this doesn't work, but I'm not sure when the problem was introduced.  Do you know which git commit is working OK?

**Comment by SonnyJim** [comment]
I think code from around this sort of commit should work:
http://github.com/bcd/freewpc/commit/f72d22343d0177558eae4340f456d138c66f0180

**Comment by bcd** [comment]
Moved defect elsewhere.
