### ISSUE TITLE
TZ Shoot again lamp being undefined

### ISSUE THREAD

**Issue by SonnyJim** [bcd/freewpc#6]
in build/mach-config.h, genmachine is creating the following entry:
# undef MACHINE_SHOOT_AGAIN_LAMP

This causes the shoot again lamp to not work, I think this happens to wcs as well.

**Comment by bcd** [comment]
Yes, I see the problem ... around line 128 of genmachine, the following line needs to be inserted:

"shoot-again" => $GLOBAL_OBJECT,

This tells genmachine that 'shoot-again' is a valid name for a special kind of lamp, and is needed in order for that keyword in the md files to be recognized.

**Comment by SonnyJim** [comment]
Cool, I've got a few other things gameplay related (lamps not switching on etc) that I could do with chatting to you about.  Do you have IRC or some kind of instant messenger?

**Comment by bcd** [comment]
The change for this has been committed.
