### ISSUE TITLE
TZ: Right Ramp Diverter fails to operate randomly

### ISSUE THREAD

**Issue by SonnyJim** [bcd/freewpc#9]
Normally the diverter works using consistantly the same power and with more than enough to move the divertor.

Very occasionally it will not activate with enough power, causing the diverter to not move.  What happens next is that the ball becomes stuck, as the ball search appears not to activate the diverter, although it may be just that it is not giving it enough power.

**Comment by bcd** [comment]
Moved defect elsewhere.
